spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/book;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  profiles:
    include: oauth
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
